#!/bin/sh
#
# This file is part of impacca. Copyright (C) 2013 and above Shogun <shogun@cowtech.it>.
# Licensed under the MIT license, which can be found at https://choosealicense.com/licenses/mit.
#

[ "$VERSION" = "" ] && VERSION="master"

case `uname -s` in
Linux)
  OS="linux"
  ;;
Darwin)
  OS="darwin"
  ;;
*)
  OS="windows"
  ;;
esac

mkdir -p /usr/local/bin

if [ "$LOCAL" = "true" ]; then
  cp -v ./dist/impacca-$OS /usr/local/bin/impacca
else 
  curl -L -o /usr/local/bin/impacca https://github.com/ShogunPanda/impacca/raw/$VERSION/dist/impacca-$OS
fi

chmod a+x /usr/local/bin/impacca
